name: "Update addons"
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    name: "Update addons"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: "Install updater"
        run: pip3 install .

      - name: "Copy addons list"
        run: cp addons.json5 /tmp/

      - uses: actions/checkout@v5
        with:
          ref: data

      - name: "Update addons"
        run: nix-mozilla-addons /tmp/addons.json5

      - uses: EndBug/add-and-commit@v9
        with: { default_author: github_actions }
